[versions]
agp = "8.13.2"
coreKtx = "1.17.0"
coroutines = "1.10.2"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.23"

composeBom = "2025.12.01"
androidXActivity = "1.12.2"
androidXConstraintlayout = "1.1.1"
androidXCoreSplashScreen = "1.2.0"
androidXLifecycle = "2.10.0"
androidXNavigation = "2.9.6"

# Hilt library
hiltAndroid = "2.57.2"
hiltAndroidArtifacts = "1.3.0"

# Third Party
# Networking
squareupRetrofit = "3.0.0"
squareupOkHttp3 = "4.12.0"
# Image Loading (For Crypto Icons)
coilKT = "2.4.0"

# Testing
coroutinesTest = "1.10.2"
espressoCore = "3.0.0"
junit = "4.13.2"
androidXJUnit = "1.0.0"
mockk = "1.14.7"
googleTruth = "1.4.5"
turbine = "1.2.1"

[libraries]
# Core, Kotlin, Coroutines
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }

# Pure Androidx
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidXActivity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidXConstraintlayout" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidXCoreSplashScreen" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidXLifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidXLifecycle" }

androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidXNavigation" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltAndroid" }
androidx-hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltAndroidArtifacts" }

# Third Party
squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "squareupRetrofit" }
squareup-retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "squareupRetrofit" }
squareup-okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "squareupOkHttp3" }

coil-kt = { group= "io.coil-kt", name = "coil-compose", version.ref = "coilKT" }

# Testing Libraries
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidXJUnit" }
hilt-android-testing = { group="com.google.dagger", name = "hilt-android-testing", version.ref = "hiltAndroid" }
hilt-android-compiler = { group="com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltAndroid" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
test-mockk-default = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
test-mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }
test-mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
test-cash-turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
test-google-truth = { group = "com.google.truth", name = "truth", version.ref = "googleTruth" }
test-squareup-okhttp3-mockServer = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "squareupOkHttp3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
hilt-gradle = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }